"""change the type of the phone number

Revision ID: a796899291a5
Revises: f17e25ad6d4e
Create Date: 2026-07-08 06:59:06.717677

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a796899291a5'
down_revision: Union[str, Sequence[str], None] = 'f17e25ad6d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('shipment', 'client_contact_number',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('seller', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('delivery_partner', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
