"""add a tag and link table

Revision ID: c2f9956f3c6f
Revises: a6c4b3559f7e
Create Date: 2026-07-11 07:42:41.038240

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = 'c2f9956f3c6f'
down_revision: Union[str, Sequence[str], None] = 'a6c4b3559f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    op.execute(
        sa.text(
            """
            INSERT INTO tag (id, name, instruction) VALUES
            (gen_random_uuid(), 'EXPRESS', 'Handle with priority'),
            (gen_random_uuid(), 'STANDARD', 'Regular delivery timeframe'),
            (gen_random_uuid(), 'FRAGILE', 'Handle with care'),
            (gen_random_uuid(), 'HEAVY', 'Weight exceeds 20kg'),
            (gen_random_uuid(), 'INTERNATIONAL', 'Package requires customs clearance'),
            (gen_random_uuid(), 'DOMESTIC', 'For delivery within the same country'),
            (gen_random_uuid(), 'TEMPERATURE_CONTROLLED', 'Keep within specified temperature range'),
            (gen_random_uuid(), 'GIFT', 'Contains gift items, handle with care'),
            (gen_random_uuid(), 'RETURN', 'Package is being returned to sender'),
            (gen_random_uuid(), 'DOCUMENTS', 'Contains important documents');
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
