"""add a Email service

Revision ID: d00dcddba7bf
Revises: af0eb7c6044c
Create Date: 2026-07-04 07:32:33.391103

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00dcddba7bf'
down_revision: Union[str, Sequence[str], None] = 'af0eb7c6044c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('client_contact_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_number')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
