"""add a user email verification

Revision ID: f17e25ad6d4e
Revises: 
Create Date: 2026-07-06 07:28:38.975920

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17e25ad6d4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
